name: Java Test and Coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Tests and Upload Coverage to Codecov
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v1
        with:
          java-version: 21

      - name: Install dependencies
        run: mvn install -DskipTests=tr ue -Dmaven.javadoc.skip=true -B -V

      - name: Run tests and collect coverage
        run: mvn -B test -Ptest -Dspring.profiles.active=test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: javiertelioz/hexagonal-architecture-java